version: "3.8"
networks:
  default:
    ipam:
      config:
        - subnet: 172.16.0.0/23 # In order to specify static IPs, we must explicitly declare subnet.
          #ip_range: 172.16.0.0/24 # Range for dynamic IPs. We'll make sure to assign static IPs outside this range.
          # docs: https://docs.docker.com/compose/compose-file/compose-file-v2/#ipam
          # As of this writing, `ip_range` is not supported in v3, thus we will explictly specify IP
services:
  dnsmasq:
    container_name: "dnsmasq"
    image: strm/dnsmasq
    volumes:
      - "./dnsmasq.conf:/etc/dnsmasq.conf" #this file has wildcard dns entries for localstack
    # ports:
    # - 53:53/udp
    cap_add:
      - NET_ADMIN
    networks:
      default:
        ipv4_address: 172.16.1.253 # Static IP here makes it possible in docker comspose v3 to point other containers' dns here.

  localstack:
    container_name: "localstack"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      - SERVICES=s3,lambda,dynamodb,cloudwatch,logs
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_DOCKER_DNS=172.16.1.253
      - LAMBDA_EXECUTOR=docker-reuse
      - DEFAULT_REGION=eu-central-1
      - PERSISTENCE=0
      - DEBUG=false
      # - LOCALSTACK_HOSTNAME=localhost.localstack.cloud
      # - HOSTNAME_FROM_LAMBDA=localhost.localstack.cloud
      # - DNS_ADDRESS=127.0.0.1
      # - DNS_LOCAL_NAME_PATTERNS='.*(ecr|lambda-url).*.localhost.localstack.cloud'
      # - HOSTNAME_EXTERNAL=localhost.localstack.cloud
      # - HOSTNAME=localhost.localstack.cloud
    volumes:
      - localstack-vol:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      default:
        ipv4_address: 172.16.1.252 # Static IP here makes dnsmasq config easy to write and compatible with v3 as v3 dont have range

volumes:
  localstack-vol:
