# fly.toml file generated for billowing-river-3253 on 2022-11-09T17:01:52Z

app = "billowing-river-3253"

[[services]]
internal_port = 8080
protocol = "tcp"

[[services.ports]]
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443
