[package]
name = "dto"
version = "0.0.1"
edition = "2021"
description = "Experimental with proc macros"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
syn = "2.0.48"
quote = "1.0.35"
