[package]
name = "core"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "^0.4"
serde = { version = "1", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
aws-config = "0.49"
aws-sdk-dynamodb = "0.19"
aws-types = "0.49"

dto = { path = "../dto" }
