# FROM rust:slim-buster AS builder

# WORKDIR /prod
# COPY Cargo.lock .
# COPY Cargo.toml .
# RUN mkdir .cargo
# This is the trick to speed up the building process.
# RUN cargo vendor > .cargo/config

# COPY . .
# RUN cargo build --release --bin local_graphql 

# Use any runner as you want
# But beware that some images have old glibc which makes rust unhappy
# FROM fedora:34 AS runner
FROM alpine:3 AS runner
COPY /target/x86_64-unknown-linux-musl/release/local_graphql /bin
# COPY --from=builder /prod/target/release/local_graphql /bin

EXPOSE 8080

ENTRYPOINT [ "/bin/local_graphql" ]