version: "3.8"
networks:
  default:
    ipam:
      config:
        - subnet: 172.16.0.0/23
services:
  backend:
    build:
      # dockerfile: ./DNS-Env-Dockerfile
      context: backend
      target: development
    depends_on:
      - localstack
      - dnsmasq
  dnsmasq:
    container_name: "dnsmasq"
    build:
      dockerfile: ./DNS-Dockerfile
    cap_add:
      - NET_ADMIN
    networks:
      default:
        ipv4_address: 172.16.1.253

  localstack:
    container_name: "localstack"
    image: localstack/localstack
    ports:
      - "0.0.0.0:4566:4566"
      # - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      - SERVICES=s3,lambda,dynamodb,cloudwatch,logs
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_DOCKER_DNS=172.16.1.253
      - LAMBDA_EXECUTOR=docker-reuse
      - DEFAULT_REGION=eu-central-1
      - PERSISTENCE=0
      - DEBUG=false
    volumes:
      - localstack-vol:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      default:
        ipv4_address: 172.16.1.252

volumes:
  localstack-vol:
