name: Rust

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Cache Dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
    - name: Install musl
      run: sudo apt-get update && sudo apt-get install -y musl musl-dev musl-tools
    - name: Setup Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: clippy
        target: x86_64-unknown-linux-musl
    - name: Install required cargo
      run: cargo install clippy-sarif sarif-fmt
    - name: Run rust-clippy
      run:
        cargo clippy
        --all-features
        --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
      continue-on-error: true
    - name: Upload analysis results to GitHub
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: rust-clippy-results.sarif
        wait-for-processing: true
      
    - name: Test
      run: make test
    - name: Build Release
      run: make release
    - name: Package
      run: make package
    - name: Upload Lambdas
      uses: actions/upload-artifact@v2
      with:
        name: lambdas-${{ runner.os }}.zip
        path: |
          deploy/*.zip
